name: Run Selenium End-to-End Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-selenium-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ui_automation/selenium/requirements.txt

    # Running the script
    - name: Run Selenium Test
      run: |
        python ui_automation/selenium/auto_pilot_code.py

    # Check the result
    - name: Check Test Result
      run: |
        RESPONSE=$(python -c "import sys; sys.path.append('ui_automation/selenium'); import auto_pilot_code; print(auto_pilot_code.run_selenium_script())")
        echo "Response: $RESPONSE"
        if [[ "$RESPONSE" == *'"messageCode": 200'* ]]; then
          echo "Selenium tests passed successfully!"
        else
          echo "Selenium tests failed."
          exit 1